Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,25 +47,25 @@ jobs:
         if [ ${#images[@]} -gt 0 ]; then
             release_id=$(curl -s -m 6 -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/pve_kvm_images/releases/tags/images" | jq -r '.id')
             for file in "${images[@]}"; do
-                echo "\nChecking if $file already exists in release..."
-                existing_asset_id=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/pve_kvm_images/releases/$release_id/assets" | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
-                if [ -n "$existing_asset_id" ]; then
-                    echo "\nAsset $file already exists in release, deleting existing asset..."
-                    delete_response=$(curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/oneclickvirt/pve_kvm_images/releases/assets/$existing_asset_id")
-                    echo "\n$delete_response"
-                    if [ $? -eq 0 ] && ! echo "$delete_response" | grep -q "error"; then
-                        echo "\nExisting asset deleted successfully."
-                    else
-                        echo "\nFailed to delete existing asset. Skipping file upload..."
-                        rm -rf $file
-                        continue
-                    fi
-                else
-                    echo "No $file file."
-                fi
                 echo "Building and uploading images"
                 ./rebuild_qcow2.sh $file
                 if [ -f "$file" ] && [ $(stat -c %s "$file") -gt 10485760 ]; then
+                    echo "\nChecking if $file already exists in release..."
+                    existing_asset_id=$(curl -s -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/oneclickvirt/pve_kvm_images/releases/$release_id/assets" | jq -r --arg name "$(basename "$file")" '.[] | select(.name == $name) | .id')
+                    if [ -n "$existing_asset_id" ]; then
+                        echo "\nAsset $file already exists in release, deleting existing asset..."
+                        delete_response=$(curl -s -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/oneclickvirt/pve_kvm_images/releases/assets/$existing_asset_id")
+                        echo "\n$delete_response"
+                        if [ $? -eq 0 ] && ! echo "$delete_response" | grep -q "error"; then
+                            echo "\nExisting asset deleted successfully."
+                        else
+                            echo "\nFailed to delete existing asset. Skipping file upload..."
+                            rm -rf $file
+                            continue
+                        fi
+                    else
+                        echo "No $file file."
+                    fi
                     echo "\nUploading $file to release..."
                     curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                       -H "Content-Type: application/zip" \
